spring:
  main:
    banner-mode: off
  shell:
    noninteractive:
      primary-command: termdeck
logging:
  pattern:
    console:
  file:
    name: termdeck.log
  level:
    # root: debug
    com:
      github:
        jvalkeal: debug
    # org:
    #   springframework:
    #     shell: debug
